# Generated by Django 3.1.5 on 2021-02-03 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_class_app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_class_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.IntegerField(default=my_class_app.models.LessonStatus['NEW']),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=4000)),
                ('is_read', models.BooleanField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_from', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
